In [1]:
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

#data source https://data.cityofnewyork.us/Public-Safety/NYC-crime/qb7u-rbmr

In [2]:

df1 = pd.read_csv('/content/drive/MyDrive/NYPD_Complaint_Data_Historic.csv').drop(['CMPLNT_TO_DT','CMPLNT_NUM','CMPLNT_TO_TM','CRM_ATPT_CPTD_CD','SUSP_SEX','TRANSIT_DISTRICT','STATION_NAME','VIC_AGE_GROUP','VIC_RACE','VIC_SEX','ADDR_PCT_CD','RPT_DT','HADEVELOPT','HOUSING_PSA','JURISDICTION_CODE','CMPLNT_FR_TM','SUSP_AGE_GROUP','SUSP_RACE','PARKS_NM'],axis=1)

In [3]:
df1

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,FRONT OF,PARKING LOT/GARAGE (PUBLIC),N.Y. POLICE DEPT,"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)",PATROL BORO MAN NORTH
1,02/06/2018,341,PETIT LARCENY,333.0,"LARCENY,PETIT FROM STORE-SHOPL",MISDEMEANOR,BRONX,INSIDE,DEPARTMENT STORE,N.Y. POLICE DEPT,"1,009,690","257,590",40.873671,-73.908014,"(40.873671035, -73.908013649)",PATROL BORO BRONX
2,11/21/2018,341,PETIT LARCENY,321.0,"LARCENY,PETIT FROM AUTO",MISDEMEANOR,BROOKLYN,FRONT OF,STREET,N.Y. POLICE DEPT,"1,016,034","176,756",40.651782,-73.885457,"(40.651782232, -73.885456761)",PATROL BORO BKLYN NORTH
3,06/09/2018,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,AGGRAVATED HARASSMENT 2,MISDEMEANOR,MANHATTAN,INSIDE,RESIDENCE - APT. HOUSE,N.Y. POLICE DEPT,"985,717","215,911",40.759310,-73.994706,"(40.759310399, -73.994706072)",PATROL BORO MAN SOUTH
4,11/10/2018,341,PETIT LARCENY,333.0,"LARCENY,PETIT FROM STORE-SHOPL",MISDEMEANOR,MANHATTAN,INSIDE,CHAIN STORE,N.Y. POLICE DEPT,"992,359","217,816",40.764536,-73.970728,"(40.764535539, -73.970728388)",PATROL BORO MAN NORTH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7825494,05/01/2008,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",MISDEMEANOR,MANHATTAN,FRONT OF,STREET,N.Y. POLICE DEPT,"985,209","214,992",40.756788,-73.996540,"(40.756788048, -73.996539912)",PATROL BORO MAN SOUTH
7825495,05/18/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,MISDEMEANOR,STATEN ISLAND,NaN,STREET,N.Y. POLICE DEPT,"955,828","149,854",40.577953,-74.102317,"(40.577953265, -74.102316756)",PATROL BORO STATEN ISLAND
7825496,11/19/2018,109,GRAND LARCENY,421.0,"LARCENY,GRAND FROM VEHICLE/MOTORCYCLE",FELONY,QUEENS,FRONT OF,STREET,N.Y. POLICE DEPT,"1,022,372","210,067",40.743188,-73.862427,"(40.743188053, -73.862427079)",PATROL BORO QUEENS NORTH
7825497,02/03/2018,578,HARRASSMENT 2,638.0,"HARASSMENT,SUBD 3,4,5",VIOLATION,STATEN ISLAND,FRONT OF,RESIDENCE-HOUSE,N.Y. POLICE DEPT,"959,533","155,574",40.593665,-74.089000,"(40.593664627, -74.089000194)",PATROL BORO STATEN ISLAND
7825498,01/05/2018,233,SEX CRIMES,175.0,"SEXUAL ABUSE 3,2",MISDEMEANOR,BROOKLYN,FRONT OF,STREET,N.Y. POLICE DEPT,"999,634","190,253",40.688872,-73.944529,"(40.688872153, -73.944529032)",PATROL BORO BKLYN NORTH

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7825499 entries, 0 to 7825498
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   CMPLNT_FR_DT       object
 1   KY_CD              int64
 2   OFNS_DESC          object
 3   PD_CD              float64
 4   PD_DESC            object
 5   LAW_CAT_CD         object
 6   BORO_NM            object
 7   LOC_OF_OCCUR_DESC  object
 8   PREM_TYP_DESC      object
 9   JURIS_DESC         object
 10  X_COORD_CD         object
 11  Y_COORD_CD         object
 12  Latitude           float64
 13  Longitude          float64
 14  Lat_Lon            object
 15  PATROL_BORO        object
dtypes: float64(3), int64(1), object(12)
memory usage: 955.3+ MB

In [5]:
df1.isna().sum()

CMPLNT_FR_DT             655
KY_CD                      0
OFNS_DESC              18832
PD_CD                   6761
PD_DESC                 6761
LAW_CAT_CD                 0
BORO_NM                12480
LOC_OF_OCCUR_DESC    1618063
PREM_TYP_DESC          42015
JURIS_DESC                 0
X_COORD_CD             17339
Y_COORD_CD             17339
Latitude               17339
Longitude              17339
Lat_Lon                17339
PATROL_BORO             7218
dtype: int64

In [6]:
df1.describe()

              KY_CD         PD_CD      Latitude     Longitude
count  7.825499e+06  7.818738e+06  7.808160e+06  7.808160e+06
mean   2.968756e+02  4.126822e+02  4.073517e+01 -7.392551e+01
std    1.511127e+02  2.176568e+02  8.609054e-02  7.825796e-02
min    1.010000e+02  1.000000e+02  4.011271e+01 -7.751921e+01
25%    1.170000e+02  2.540000e+02  4.067280e+01 -7.397287e+01
50%    3.410000e+02  3.800000e+02  4.073236e+01 -7.392721e+01
75%    3.510000e+02  6.370000e+02  4.081215e+01 -7.388291e+01
max    8.810000e+02  9.750000e+02  5.965727e+01 -7.368479e+01

In [7]:
df1=df1.drop_duplicates()

In [7]:
df1.isna().sum()

CMPLNT_FR_DT             655
KY_CD                      0
OFNS_DESC              18386
PD_CD                   6474
PD_DESC                 6474
LAW_CAT_CD                 0
BORO_NM                12089
LOC_OF_OCCUR_DESC    1575036
PREM_TYP_DESC          41089
JURIS_DESC                 0
X_COORD_CD             12995
Y_COORD_CD             12995
Latitude               12995
Longitude              12995
Lat_Lon                12995
PATROL_BORO             6899
dtype: int64

In [13]:
df1=df1.drop(['LOC_OF_OCCUR_DESC'],axis=1)

In [14]:
df1

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,PARKING LOT/GARAGE (PUBLIC),N.Y. POLICE DEPT,"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)",PATROL BORO MAN NORTH
2,11/21/2018,341,PETIT LARCENY,321.0,"LARCENY,PETIT FROM AUTO",MISDEMEANOR,BROOKLYN,STREET,N.Y. POLICE DEPT,"1,016,034","176,756",40.651782,-73.885457,"(40.651782232, -73.885456761)",PATROL BORO BKLYN NORTH
5,03/12/2018,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",FELONY,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"1,001,575","232,339",40.804384,-73.937422,"(40.804384046, -73.937421669)",PATROL BORO MAN NORTH
6,04/07/2013,118,DANGEROUS WEAPONS,793.0,WEAPONS POSSESSION 3,FELONY,QUEENS,STREET,N.Y. POLICE DEPT,"1,039,793","195,661",40.703555,-73.799677,"(40.703554914, -73.799677386)",PATROL BORO QUEENS SOUTH
7,09/12/2018,121,CRIMINAL MISCHIEF & RELATED OF,269.0,"MISCHIEF,CRIMINAL, UNCL 2ND",FELONY,BRONX,FAST FOOD,N.Y. POLICE DEPT,"1,010,008","250,297",40.853653,-73.906892,"(40.853653041, -73.906891831)",PATROL BORO BRONX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7825494,05/01/2008,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"985,209","214,992",40.756788,-73.996540,"(40.756788048, -73.996539912)",PATROL BORO MAN SOUTH
7825495,05/18/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,MISDEMEANOR,STATEN ISLAND,STREET,N.Y. POLICE DEPT,"955,828","149,854",40.577953,-74.102317,"(40.577953265, -74.102316756)",PATROL BORO STATEN ISLAND
7825496,11/19/2018,109,GRAND LARCENY,421.0,"LARCENY,GRAND FROM VEHICLE/MOTORCYCLE",FELONY,QUEENS,STREET,N.Y. POLICE DEPT,"1,022,372","210,067",40.743188,-73.862427,"(40.743188053, -73.862427079)",PATROL BORO QUEENS NORTH
7825497,02/03/2018,578,HARRASSMENT 2,638.0,"HARASSMENT,SUBD 3,4,5",VIOLATION,STATEN ISLAND,RESIDENCE-HOUSE,N.Y. POLICE DEPT,"959,533","155,574",40.593665,-74.089000,"(40.593664627, -74.089000194)",PATROL BORO STATEN ISLAND
7825498,01/05/2018,233,SEX CRIMES,175.0,"SEXUAL ABUSE 3,2",MISDEMEANOR,BROOKLYN,STREET,N.Y. POLICE DEPT,"999,634","190,253",40.688872,-73.944529,"(40.688872153, -73.944529032)",PATROL BORO BKLYN NORTH

In [15]:
df1=df1.dropna()

In [16]:
df3=df1.dropna()

In [17]:
df2 = df1[~(df1['PATROL_BORO'] == "PATROL BORO MAN NORTH")].index 
df4 = df3[~(df3['PATROL_BORO'] == "PATROL BORO MAN SOUTH")].index 

df1.drop(df2, inplace = True)
df3.drop(df4, inplace = True)
df1.append(df3, ignore_index=True)

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,PARKING LOT/GARAGE (PUBLIC),N.Y. POLICE DEPT,"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)",PATROL BORO MAN NORTH
1,03/12/2018,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",FELONY,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"1,001,575","232,339",40.804384,-73.937422,"(40.804384046, -73.937421669)",PATROL BORO MAN NORTH
2,09/26/2018,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",FELONY,MANHATTAN,STREET,N.Y. POLICE DEPT,"997,529","232,162",40.803905,-73.952037,"(40.803905237, -73.952036608)",PATROL BORO MAN NORTH
3,03/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",MISDEMEANOR,MANHATTAN,MAILBOX OUTSIDE,N.Y. POLICE DEPT,"999,569","227,672",40.791578,-73.944678,"(40.791578107, -73.944678204)",PATROL BORO MAN NORTH
4,10/10/2018,341,PETIT LARCENY,343.0,"LARCENY,PETIT OF BICYCLE",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"989,062","220,601",40.772182,-73.982628,"(40.772182051, -73.98262839)",PATROL BORO MAN NORTH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782196,11/12/2018,109,GRAND LARCENY,404.0,"LARCENY,GRAND FROM PERSON,PERSONAL ELECTRONIC ...",FELONY,MANHATTAN,STREET,N.Y. POLICE DEPT,"985,274","213,756",40.753396,-73.996305,"(40.753395534, -73.996305482)",PATROL BORO MAN SOUTH
782197,07/15/2018,344,ASSAULT 3 & RELATED OFFENSES,113.0,"MENACING,UNCLASSIFIED",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"984,966","217,544",40.763793,-73.997417,"(40.763792658, -73.997416757)",PATROL BORO MAN SOUTH
782198,04/24/2018,341,PETIT LARCENY,321.0,"LARCENY,PETIT FROM AUTO",MISDEMEANOR,MANHATTAN,BUS (OTHER),N.Y. POLICE DEPT,"989,519","217,704",40.764230,-73.980981,"(40.764230276, -73.980980725)",PATROL BORO MAN SOUTH
782199,06/26/2018,341,PETIT LARCENY,343.0,"LARCENY,PETIT OF BICYCLE",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"991,046","214,324",40.754952,-73.975472,"(40.754951998, -73.975471778)",PATROL BORO MAN SOUTH
782200,05/01/2008,235,DANGEROUS DRUGS,511.0,"CONTROLLED SUBSTANCE, POSSESSI",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"985,209","214,992",40.756788,-73.996540,"(40.756788048, -73.996539912)",PATROL BORO MAN SOUTH

In [18]:
df1

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,PARKING LOT/GARAGE (PUBLIC),N.Y. POLICE DEPT,"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)",PATROL BORO MAN NORTH
5,03/12/2018,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",FELONY,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"1,001,575","232,339",40.804384,-73.937422,"(40.804384046, -73.937421669)",PATROL BORO MAN NORTH
10,09/26/2018,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",FELONY,MANHATTAN,STREET,N.Y. POLICE DEPT,"997,529","232,162",40.803905,-73.952037,"(40.803905237, -73.952036608)",PATROL BORO MAN NORTH
20,03/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",MISDEMEANOR,MANHATTAN,MAILBOX OUTSIDE,N.Y. POLICE DEPT,"999,569","227,672",40.791578,-73.944678,"(40.791578107, -73.944678204)",PATROL BORO MAN NORTH
36,10/10/2018,341,PETIT LARCENY,343.0,"LARCENY,PETIT OF BICYCLE",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"989,062","220,601",40.772182,-73.982628,"(40.772182051, -73.98262839)",PATROL BORO MAN NORTH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7825341,05/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",MISDEMEANOR,MANHATTAN,PARK/PLAYGROUND,N.Y. POLICE DEPT,"1,001,557","228,247",40.793153,-73.937497,"(40.793152657, -73.937497233)",PATROL BORO MAN NORTH
7825368,02/26/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,MISDEMEANOR,MANHATTAN,RESIDENCE - PUBLIC HOUSING,N.Y. HOUSING POLICE,"1,002,118","242,744",40.832942,-73.935433,"(40.832941761, -73.935432593)",PATROL BORO MAN NORTH
7825399,06/04/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",MISDEMEANOR,MANHATTAN,PRIVATE/PAROCHIAL SCHOOL,N.Y. POLICE DEPT,"992,402","227,087",40.789982,-73.970562,"(40.789981956, -73.970561913)",PATROL BORO MAN NORTH
7825486,04/24/2018,235,DANGEROUS DRUGS,567.0,"MARIJUANA, POSSESSION 4 & 5",MISDEMEANOR,MANHATTAN,RESIDENCE - PUBLIC HOUSING,N.Y. HOUSING POLICE,"999,116","226,853",40.789331,-73.946316,"(40.789330946, -73.946315985)",PATROL BORO MAN NORTH
7825491,01/31/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,MISDEMEANOR,MANHATTAN,GAS STATION,N.Y. POLICE DEPT,"1,001,192","247,161",40.845067,-73.938768,"(40.845066966, -73.938767684)",PATROL BORO MAN NORTH

In [19]:
df2 = df1[~(df1['PATROL_BORO'] == "PATROL BORO MAN NORTH")].index 
df1.drop(df2, inplace = True)
df1.head()

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,PARKING LOT/GARAGE (PUBLIC),N.Y. POLICE DEPT,"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)",PATROL BORO MAN NORTH
5,03/12/2018,113,FORGERY,729.0,"FORGERY,ETC.,UNCLASSIFIED-FELO",FELONY,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"1,001,575","232,339",40.804384,-73.937422,"(40.804384046, -73.937421669)",PATROL BORO MAN NORTH
10,09/26/2018,106,FELONY ASSAULT,109.0,"ASSAULT 2,1,UNCLASSIFIED",FELONY,MANHATTAN,STREET,N.Y. POLICE DEPT,"997,529","232,162",40.803905,-73.952037,"(40.803905237, -73.952036608)",PATROL BORO MAN NORTH
20,03/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,"CRIMINAL MISCHIEF 4TH, GRAFFIT",MISDEMEANOR,MANHATTAN,MAILBOX OUTSIDE,N.Y. POLICE DEPT,"999,569","227,672",40.791578,-73.944678,"(40.791578107, -73.944678204)",PATROL BORO MAN NORTH
36,10/10/2018,341,PETIT LARCENY,343.0,"LARCENY,PETIT OF BICYCLE",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"989,062","220,601",40.772182,-73.982628,"(40.772182051, -73.98262839)",PATROL BORO MAN NORTH

In [20]:
df4 = df3[~(df3['PATROL_BORO'] == "PATROL BORO MAN SOUTH")].index 
df3.drop(df4, inplace = True)
df3.head()

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,LAW_CAT_CD,BORO_NM,PREM_TYP_DESC,JURIS_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon,PATROL_BORO
14,12/01/2018,359,OFFENSES AGAINST PUBLIC ADMINI,759.0,"PUBLIC ADMINISTATION,UNCLASS M",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"990,112","209,137",40.740716,-73.978848,"(40.740715654, -73.978847503)",PATROL BORO MAN SOUTH
98,02/25/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,"MISCHIEF, CRIMINAL 4, OF MOTOR",MISDEMEANOR,MANHATTAN,STREET,N.Y. POLICE DEPT,"982,777","204,727",40.728613,-74.005316,"(40.728613108, -74.005316033)",PATROL BORO MAN SOUTH
116,02/27/2018,109,GRAND LARCENY,406.0,"LARCENY,GRAND FROM PERSON, BAG OPEN/DIP",FELONY,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"982,806","201,821",40.720637,-74.005211,"(40.720636846, -74.005210778)",PATROL BORO MAN SOUTH
119,05/18/2018,578,HARRASSMENT 2,637.0,"HARASSMENT,SUBD 1,CIVILIAN",VIOLATION,MANHATTAN,RESIDENCE - PUBLIC HOUSING,N.Y. HOUSING POLICE,"984,221","198,452",40.711390,-74.000106,"(40.711389864, -74.000106051)",PATROL BORO MAN SOUTH
152,02/25/2018,233,SEX CRIMES,175.0,"SEXUAL ABUSE 3,2",MISDEMEANOR,MANHATTAN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,"992,411","215,025",40.756875,-73.970544,"(40.756874911, -73.970544057)",PATROL BORO MAN SOUTH

In [21]:
df1=df1.drop(['PATROL_BORO','PD_DESC','BORO_NM','LAW_CAT_CD','JURIS_DESC'],axis=1)

In [22]:
df3=df3.drop(['PATROL_BORO','PD_DESC','BORO_NM','LAW_CAT_CD','JURIS_DESC'],axis=1)

In [23]:
df1

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PREM_TYP_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
0,03/29/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,PARKING LOT/GARAGE (PUBLIC),"1,000,565","234,704",40.810877,-73.941064,"(40.810877241, -73.941064151)"
5,03/12/2018,113,FORGERY,729.0,TRANSIT - NYC SUBWAY,"1,001,575","232,339",40.804384,-73.937422,"(40.804384046, -73.937421669)"
10,09/26/2018,106,FELONY ASSAULT,109.0,STREET,"997,529","232,162",40.803905,-73.952037,"(40.803905237, -73.952036608)"
20,03/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,MAILBOX OUTSIDE,"999,569","227,672",40.791578,-73.944678,"(40.791578107, -73.944678204)"
36,10/10/2018,341,PETIT LARCENY,343.0,STREET,"989,062","220,601",40.772182,-73.982628,"(40.772182051, -73.98262839)"
...,...,...,...,...,...,...,...,...,...,...
7825341,05/26/2018,351,CRIMINAL MISCHIEF & RELATED OF,259.0,PARK/PLAYGROUND,"1,001,557","228,247",40.793153,-73.937497,"(40.793152657, -73.937497233)"
7825368,02/26/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,RESIDENCE - PUBLIC HOUSING,"1,002,118","242,744",40.832942,-73.935433,"(40.832941761, -73.935432593)"
7825399,06/04/2018,351,CRIMINAL MISCHIEF & RELATED OF,258.0,PRIVATE/PAROCHIAL SCHOOL,"992,402","227,087",40.789982,-73.970562,"(40.789981956, -73.970561913)"
7825486,04/24/2018,235,DANGEROUS DRUGS,567.0,RESIDENCE - PUBLIC HOUSING,"999,116","226,853",40.789331,-73.946316,"(40.789330946, -73.946315985)"
7825491,01/31/2018,344,ASSAULT 3 & RELATED OFFENSES,101.0,GAS STATION,"1,001,192","247,161",40.845067,-73.938768,"(40.845066966, -73.938767684)"

In [25]:
df3

,CMPLNT_FR_DT,KY_CD,OFNS_DESC,PD_CD,PREM_TYP_DESC,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lat_Lon
14,12/01/2018,359,OFFENSES AGAINST PUBLIC ADMINI,759.0,STREET,"990,112","209,137",40.740716,-73.978848,"(40.740715654, -73.978847503)"
98,02/25/2018,351,CRIMINAL MISCHIEF & RELATED OF,254.0,STREET,"982,777","204,727",40.728613,-74.005316,"(40.728613108, -74.005316033)"
116,02/27/2018,109,GRAND LARCENY,406.0,TRANSIT - NYC SUBWAY,"982,806","201,821",40.720637,-74.005211,"(40.720636846, -74.005210778)"
119,05/18/2018,578,HARRASSMENT 2,637.0,RESIDENCE - PUBLIC HOUSING,"984,221","198,452",40.711390,-74.000106,"(40.711389864, -74.000106051)"
152,02/25/2018,233,SEX CRIMES,175.0,TRANSIT - NYC SUBWAY,"992,411","215,025",40.756875,-73.970544,"(40.756874911, -73.970544057)"
...,...,...,...,...,...,...,...,...,...,...
7825370,11/12/2018,109,GRAND LARCENY,404.0,STREET,"985,274","213,756",40.753396,-73.996305,"(40.753395534, -73.996305482)"
7825411,07/15/2018,344,ASSAULT 3 & RELATED OFFENSES,113.0,STREET,"984,966","217,544",40.763793,-73.997417,"(40.763792658, -73.997416757)"
7825432,04/24/2018,341,PETIT LARCENY,321.0,BUS (OTHER),"989,519","217,704",40.764230,-73.980981,"(40.764230276, -73.980980725)"
7825488,06/26/2018,341,PETIT LARCENY,343.0,STREET,"991,046","214,324",40.754952,-73.975472,"(40.754951998, -73.975471778)"
7825494,05/01/2008,235,DANGEROUS DRUGS,511.0,STREET,"985,209","214,992",40.756788,-73.996540,"(40.756788048, -73.996539912)"

In [27]:
pd.concat([df1, df3], ignore_index=True).to_csv('NewYorkDataSetFinal.csv')